### ISSUE TITLE
Release 0.37.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/postcss-css-in-js#15]
As `@stylelint/postcss-css-in-js`.

**Comment by hudochenkov** [comment]
What blocks us?

**Comment by jeddy3** [comment]
Blocked on a few preparation issues: https://github.com/stylelint/postcss-css-in-js/issues/10, https://github.com/stylelint/postcss-css-in-js/issues/13 and https://github.com/stylelint/postcss-css-in-js/issues/14

**Comment by jeddy3** [comment]
- Merge https://github.com/stylelint/postcss-css-in-js/pull/25
- Add `npm run release` run-script command using `np`

Are we going with a patch release of 0.36.5, or do we jump to 1.0.0?

Is there a relationship between the release number and that of `postcss-syntax`, or are they independent?

**Comment by jeddy3** [comment]
I believe we can release after https://github.com/stylelint/postcss-css-in-js/pull/29 is merged.

**Comment by jeddy3** [comment]
Done, but `np` tripped up:

```
✔ Publishing package using npm
  ✖ Enabling two-factor authentication
    → npm ERR!     /Users/jeddy3/.npm/_logs/2020-04-06T11_24_48_290Z-debug.log
    Pushing tags
    Creating release draft on GitHub

✖ Command failed with exit code 1: npm access 2fa-required @stylelint/postcss-css-in-js --otp 380480
npm ERR! code E503
npm ERR! 503 Service Unavailable - POST https://registry.npmjs.org/-/package/%40stylelint%2Fpostcss-css-in-js/access - Service Unavailable
```

Any ideas?

I manually pushed the tags and created the GitHub release.

**Comment by jeddy3** [comment]
Looks to be an upstream issue: https://github.com/sindresorhus/np/issues/504
